file-cache.o: file-cache.cpp
	g++ file-cache.cpp -o bin/file-cache -Wall -O0

file-read.o: file-read.cpp
	g++ file-read.cpp -o bin/file-read -Wall -O0

contention.o: contention.cpp
	g++ contention.cpp -o bin/contention -Wall -O0