file-cache: file-cache.cpp
	g++ file-cache.cpp -o bin/file-cache -Wall -O0

file-read: file-read.cpp
	g++ file-read.cpp -o bin/file-read -Wall -O0

contention: contention.cpp
	g++ contention.cpp -o bin/contention -Wall -O0

remote-file-read-client: remote-file-read-client.cpp
	g++ remote-file-read-client.cpp -o bin/remote-file-read-client -Wall -O0

remote-file-read-server: remote-file-read-server.cpp
	g++ remote-file-read-server.cpp -o bin/remote-file-read-server -Wall -O0

all: file-cache file-read contention remote-file-read-client remote-file-read-server