measurement: measurement.cpp
	g++ measurement.cpp -o bin/measurement -Wall -O0

procedure-call: procedure-call.cpp
	g++ procedure-call.cpp -o bin/procedure-call -Wall -O0

system-call: system-call.cpp
	g++ system-call.cpp -o bin/system-call -Wall -O0

task-creation: task-creation.cpp
	g++ task-creation.cpp -o bin/task-creation -Wall -O0 -pthread

context-switch: context-switch.cpp
	g++ context-switch.cpp -o bin/context-switch -Wall -O0 -pthread

all: measurement procedure-call system-call task-creation context-switch