connection-client: connection-client.cpp
	g++ connection-client.cpp -o bin/connection-client -Wall -O0

connection-server: connection-server.cpp
	g++ connection-server.cpp -o bin/connection-server -Wall -O0

peak-bandwidth-client: peak-bandwidth-client.cpp
	g++ peak-bandwidth-client.cpp -o bin/peak-bandwidth-client -Wall -O0

peak-bandwidth-server: peak-bandwidth-server.cpp
	g++ peak-bandwidth-server.cpp -o bin/peak-bandwidth-server -Wall -O0

round-trip-client: round-trip-client.cpp
	g++ round-trip-client.cpp -o bin/round-trip-client -Wall -O0

round-trip-server: round-trip-server.cpp
	g++ round-trip-server.cpp -o bin/round-trip-server -Wall -O0

all: connection-client connection-server peak-bandwidth-client peak-bandwidth-server round-trip-client round-trip-server
