connection-client.o: connection-client.cpp
	g++ connection-client.cpp -o bin/connection-client -Wall -O0

connection-server.o: connection-server.cpp
	g++ connection-server.cpp -o bin/connection-server -Wall -O0

peak-bandwidth-client.o: peak-bandwidth-client.cpp
	g++ peak-bandwidth-client.cpp -o bin/peak-bandwidth-client -Wall -O0

peak-bandwidth-server.o: peak-bandwidth-server.cpp
	g++ peak-bandwidth-server.cpp -o bin/peak-bandwidth-server -Wall -O0

round-trip-client.o: round-trip-client.cpp
	g++ round-trip-client.cpp -o bin/round-trip-client -Wall -O0

round-trip-server.o: round-trip-server.cpp
	g++ round-trip-server.cpp -o bin/round-trip-server -Wall -O0

