access-time: access-time.cpp
	g++ access-time.cpp -o bin/access-time -Wall -O0

bandwidth: bandwidth.cpp
	g++ bandwidth.cpp -o bin/bandwidth -Wall -O0

page-fault-time: page-fault-time.cpp
	g++ page-fault-time.cpp -o bin/page-fault-time -Wall -O0

all: access-time bandwidth page-fault-time