access-time.o: access-time.cpp
	g++ access-time.cpp -o bin/access-time -Wall -O0

bandwidth.o: bandwidth.cpp
	g++ bandwidth.cpp -o bin/bandwidth -Wall -O0

page-fault.o: page-fault-time.cpp
	g++ page-fault-time.cpp -o bin/page-fault-time -Wall -O0
